baseURL = 'https://dev.nairolf32.com/zer0ne'
languageCode = 'en-us'
title = 'Zer0ne'
theme = "hello-friend-ng" 
paginate = 10
rssLimit = 10
copyright = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = true
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "nair0lf32"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  description = "Welcome friend"
  keywords = "hacking, cybersecurity, ctf, nair0lf32"
  images = [""]
  homeSubtitle = "Welcome to my cybersecurity blog."
  # backgroundImage = "assets/images/background.jpg"
  # gitUrl = ""
  disableReadOtherPosts = false
  enableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = false
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  # customCSS = []
  # customJS  = []
  justifyContent = false  # Set "text-align: justify" to .post-content.
 
  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true
    topText = []
    bottomText = [
      "Powered by <a href=\"https://gohugo.io/\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/nair0lf32\">nair0lf32</a>",
      "Theme used: <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Hello-friend-ng</a>"
    ]

    [params.logo]
      logoMark     = ">"
      logoText     = "$ cd /home/"
      logoHomeLink = "/"
      logoCursorDisabled = false
      logoCursorColor    = "#FEEEDD"
      logoCursorAnimate  = "2s"

  # Colors for favicons
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"


  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  [params.portrait]
   path     = "/pictures/dark_logo.png"
   alt      = "Portrait"
   maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/florianedemessi"

  [[params.social]]
    name = "email"
    url  = "mailto:florianedem@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/nair0lf32"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/florian-edemessi/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/users/14132197/florian-edemessi"

[languages]
  [languages.en]
    title = "Zer0ne"
    subtitle = "welcome friend"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark = ">"
      logoText = "Zer0ne #"
      logoHomeLink = "/"
      logoCursorDisabled = false
      logoCursorColor    = "#0FF00D"
      logoCursorAnimate  = "2s"

    # or
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # And you can even create generic menu
    [[menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"
    [[menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
    [[menu.main]]
      identifier = "writeups"
      name       = "Writeups"
      url        = "/writeups"

